### ISSUE TITLE
Lab 2 Feedback

### ISSUE THREAD

**Issue by Dr-Crow** [Brettsmooney/cmpt-221-labs#1]
# Part 1

- Index Page
    - [X] Browsable via “/index” and “/" 
    - [X] Must use HTML to display text and links
    - [X] Must include a welcome message
- About Webpage
    - [X] Must be browsable via “/about”
    - [X] Must use HTML to display text and links
    - [X] Must include the use of a list element
- Dynamic Welcome Page for the name of a User
    - [X] Must be browsable via “/name/XXXX”
    - [X] Must provide a custom welcome message

- [X] Best practice and runnable 
    

# Part 2

- Welcome Page
    - [X] Must introduce yourself 
    - [X] Must embed a picture of yourself or something that you do like a hobby/club/etc
    - [X] Potential Employer Information
-  Digital Resume Page
    - [X] Must emulate the look of a resume
    - [X] Must NOT just use HTML paragraphs
    - [X] Must include coloring and theming of Marist College
- CSS Types
    - [X] Inline
    - [X] Internal
    - [X] External
- [X] 10 Unique HTML Elements
- [X] 3 Different Fonts
- [X] Best practice and runnable
