### ISSUE TITLE
Lab 3 Feedback

### ISSUE THREAD

**Issue by Dr-Crow** [Brettsmooney/cmpt-221-labs#2]
# Part 1

- Server
    - [X] Run Flask on port 80
    - [X] Website run on the `root` route
    - [X] File named `bootstrap.py`
    - [X] No 404 errors by linking with `url_for`
    - [X] Proper layout of files

# Part 2

- Template Inheritance
    - [X] Implement a Head(Header) Section 
    - [X] Implement a Body Section with the following child sections
        - [X] Navigation Section
        - [X] Masthead Section
        - [X] Portfolio Section
        - [X] About Section
        - [X] Contact Me Section
        - [X] Footer Section
- Customize the Masthead Section
    - [X] Replace the “start bootstrap” text with your full name
    - [X] Replace the image with a picture of you
    - [X] Replace the words, “Graphic Artist - Web Designer – Illustrator” with something that describes you. 
- Customize the Portfolio Section
    - [ ] Replace all the images with activates/clubs/hobbies that you’re into
    - [ ] Replace the text and title associated with each image
- Customize the About Section
    - [X] Replace the text with text about you
- Contact Me Section
    - [X] Don’t touch this section just yet. We will try to cover more about this section next class!
- Customize the Footer Section
    - [X] Replace the location with Marist College’s address
    - [ ] Add/remove the icons/links for the “Around the Web” section
- Customize the title
    - [ ] Make the title of the page be your full name!
- [X] Customize the “Start Bootstrap” text in the top navigation bar with “Marist College” 

- Bonus - Contact Form
    - [ ] Does the form submit work?
